# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20170103_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.IntegerField(default=3),
        ),
    ]
