# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_task_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.TextField(default=''),
        ),
    ]
